// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOMVtXM6NGOF-zJCsw3UVHfEbhwDBBTFw',
    appId: '1:86597998131:web:3badb1fc8e87bcc1ce7546',
    messagingSenderId: '86597998131',
    projectId: 'sayitwellfirebase-7b53f',
    authDomain: 'sayitwellfirebase-7b53f.firebaseapp.com',
    storageBucket: 'sayitwellfirebase-7b53f.firebasestorage.app',
    measurementId: 'G-YG6LPGMJ9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsjz9vyn10jYSiRgyPEdxPd-_v913UP9E',
    appId: '1:86597998131:android:87cd580ef6587338ce7546',
    messagingSenderId: '86597998131',
    projectId: 'sayitwellfirebase-7b53f',
    storageBucket: 'sayitwellfirebase-7b53f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrt9bMZyqju8fyu_U4c5JSsfwFVqCZoC4',
    appId: '1:86597998131:ios:75a2276692a65608ce7546',
    messagingSenderId: '86597998131',
    projectId: 'sayitwellfirebase-7b53f',
    storageBucket: 'sayitwellfirebase-7b53f.firebasestorage.app',
    iosBundleId: 'com.example.sayItWell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrt9bMZyqju8fyu_U4c5JSsfwFVqCZoC4',
    appId: '1:86597998131:ios:75a2276692a65608ce7546',
    messagingSenderId: '86597998131',
    projectId: 'sayitwellfirebase-7b53f',
    storageBucket: 'sayitwellfirebase-7b53f.firebasestorage.app',
    iosBundleId: 'com.example.sayItWell',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOMVtXM6NGOF-zJCsw3UVHfEbhwDBBTFw',
    appId: '1:86597998131:web:ebfd9e4370f69e4ace7546',
    messagingSenderId: '86597998131',
    projectId: 'sayitwellfirebase-7b53f',
    authDomain: 'sayitwellfirebase-7b53f.firebaseapp.com',
    storageBucket: 'sayitwellfirebase-7b53f.firebasestorage.app',
    measurementId: 'G-G1QFMG1Q8B',
  );

}